import React from "react";
import { Nunito } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "./globals.scss";
import { store } from "./redux/store";
import { Providers } from "./redux/Providers";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Providers store={store}>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: "inherit",
              },
            }}
          >
            <AntdRegistry>{children}</AntdRegistry>
          </ConfigProvider>
        </Providers>
      </body>
    </html>
  );
}
